.TH "OVOTEXT" "1" "0.1.0" "Marco Caselli" "User Commands"
.SH "NAME"
ovotext \- simple text editor
.SH "SYNTAX"
.LP 
\fBovotext\fR\  [files]
.SH "DESCRIPTION"
.LP 
ovotext is a simple text editor written in Lazarus/FreePascal.
.SH "OPTIONS"
.LP 
.TP 
None
.SH "AUTHORS"
.LP 
Marco Caselli<marcocas@gmail.com>
